name: 糊里糊涂的博客
description: 
meta_description: "foolchen"

markdown: kramdown
highlighter: rouge

baseurl: '/'

logo: false
paginate: 15
permalink: /:title


# Details for the RSS feed generator
url:            'foolchen.github.io'
author:         '糊里糊涂'


gems: [jekyll-paginate,kramdown]