name: 糊里糊涂
description: 
meta_description: "foolchen"

markdown: kramdown
highlighter: true

baseurl: '/'

logo: false
paginate: 15
permalink: /:title


# Details for the RSS feed generator
url:            'foolchen.github.io'
author:         'foolchen'


gems: [jekyll-paginate,kramdown]